# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e44b018a891281854ce999fd60a5da127e42d15408735e36f064e82435f67d87a9221b4b76ce76563823fd1eb3d2384cfe9516c835b5d7dc6219c89d1afbb80

test:
  secret_key_base: faa88b6c784ad1b6f1be4c625567e9ac32eb14f89a7d617932aeb20d68f0a33a7a431decfd2bea6d0892aac2036c97c0aac4fcf093fec205bf6aa0d8d41a752c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
